name = "AMDH-Mine"
author = "Lukider228"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f5d6dff0354e1299cdcdcf1ada3c7c9f4eb73683cbf898ecd4c4550879c2b3ce"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.244"
