name = "AMDH-Mine"
author = "Lukider228"
version = "1.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3c774717ecf9de77e358036c8f07dc6b03597b90986c17b700f08551377f7ecd"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.244"
